export interface IConfig {
    [key: string]: string,

    POS_DEPOSIT_TO_ADDRESS: string,
    FX_ROOT_TUNNEL: string,
    PLASMA_DEPOSIT_TO_ADDRESS: string,
    POS_ERC20_PREDICATE_PROXY: string,
    POS_ERC721_PREDICATE_PROXY: string,
    POS_ERC1155_PREDICATE_PROXY: string,
    POS_ERC20_MINTABLE_PREDICATE_PROXY: string,
    POS_ERC721_MINTABLE_PREDICATE_PROXY: string,
    POS_ERC1155_MINTABLE_PREDICATE_PROXY: string,
    POS_ETHER_PREDICATE_PROXY: string,
    POS_ROOT_CHAIN_MANAGER_PROXY: string,
    STATE_SENDER: string,
    STATE_RECEIVER: string,
    GOVERNANCE_PROXY: string,
    ROOT_CHAIN_PROXY: string,

    LOCKED_ERC20_TOPIC: string,
    LOCKED_ERC721_TOPIC: string,
    LOCKED_ERC1155_TOPIC: string,
    LOCKED_ETHER_TOPIC: string,
    LOCKED_ERC20_MINTABLE_TOPIC: string,
    LOCKED_ERC721_MINTABLE_TOPIC: string,
    LOCKED_ERC1155_MINTABLE_TOPIC: string,

    EXITED_ETHER_TOPIC: string,
    FX_ERC20_WITHDRAW_TOPIC: string,
    FX_ERC721_WITHDRAW_TOPIC: string,
    FX_ERC20_MINTABLE_WITHDRAW_TOPIC: string,
    FX_ERC721_MINTABLE_WITHDRAW_TOPIC: string,

    FX_ERC20_ROOT_TUNNEL: string,
    FX_ERC721_ROOT_TUNNEL: string,
    FX_ERC1155_ROOT_TUNNEL: string,

    FX_ERC20_TOPIC: string,
    FX_ERC721_TOPIC: string,
    FX_ERC1155_TOPIC: string,

    PLASMA_TOPIC: string,
    PLASMA_CONFIRM_WITHDRAW_TOPIC: string,
    PLASMA_EXIT_TOPIC: string,
    PLASMA_ERC20_PREDICATE: string,

    STATE_SYNCED_TOPIC: string,

    ERC20_ERC721_TRANSFER_TOPIC: string,
    NULL_ADDRESS_TOPIC: string,
    NULL_ADDRESS: string,
    ETH_ADDRESS: string,

    CUSTOM_WITHDRAW_TOPIC: string,

    PLASMA_BURN_TOPIC: string,

    CUSTOM_MAPPING_TOKEN_ADDRESS_1: string,
    CUSTOM_MAPPING_TOKEN_ADDRESS_2: string,
    CUSTOM_MAPPING_TOKEN_ADDRESS_3: string,

    CUSTOM_MAPPING_PREDICATE_ADDRESS: string,

    PLASMA_MAPPING_TOPIC: string,
    POS_MAPPING_TOPIC: string,
    FX_ERC20_MAPPING_TOPIC: string,
    FX_ERC721_MAPPING_TOPIC: string,
    FX_ERC1155_MAPPING_TOPIC: string,

    ERC20_TOKEN_TYPE: string,
    ERC721_TOKEN_TYPE: string,
    ERC1155_TOKEN_TYPE: string,
    MINTABLE_ERC20_TOKEN_TYPE: string,
    MINTABLE_ERC721_TOKEN_TYPE: string,
    MINTABLE_ERC1155_TOKEN_TYPE: string,
    CUSTOM_TOKEN_TYPE: string,

    CHECKPOINT_TOPIC: string
}
