name: Release Chainflow NPM Package
run-name: ${{ github.actor }} just pushed to ChainFlow

on:
  release:
    types: [created]
jobs:
  build:
    name: Publish ChainFlow
    runs-on: ubuntu-latest
    env: 
      working-directory: ./
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
          scope: '@maticnetwork'
      
      - name: Ensure access
        run: npm whoami --registry https://npm.pkg.github.com/
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: npm publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
