name: NPM Semantic Release

on:
  push:
    branches: ['main']

jobs:
  Deployment:
    name: Publish Chain Indexer Framework
    runs-on: ubuntu-latest
    env: 
      working-directory: ./
    permissions:
      contents: read
      packages: write
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
