name: Tests

on: 
  push:
    branches:
      - '**'

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Check ubuntu version
        run: lsb_release -a
      - name: Install dependencies
        run: yarn
      - name: Build Packages
        run: yarn run build
      - name: Run Unit Tests
        run: yarn run tests
      - name: Run Integration Tests
        run: yarn tests:integration
